### ISSUE TITLE
Economy Items - Pagination

### ISSUE THREAD

**Issue by Coryf88** [Neefay/Belligerence#3]
**Describe the bug**
The items page shows multiple pages, however attempting to change to another page results in only page 1 being displayed.

**To Reproduce**
1. Go to [Items](https://belligerence.online/items?sort=1&order=ASC&page=1)
2. Click on the next page button, or a specific page number button.
3. Notice page 1 is still displayed.

**Expected behavior**
Either selected page displayed, or erroneous pages to not be shown as an option.

**Comment by Neefay** [comment]
Could not replicate @Coryf88 , can you confirm it's still happening and in what browser?

**Comment by Neefay** [comment]
Working fine for everyone who's tested it, closing until further details.

**Comment by Coryf88** [comment]
Can confirm that this no longer occurs.
